/*# A)*/
 SELECT SUM(TOTAL_POPULATION),TIME_PERIOD FROM FACT_TABLE WHERE TIME_PERIOD='WINTER' GROUP BY (TIME_PERIOD); 
/*# B)*/
 SELECT SUM(TOTAL_SERVICE_COST),COST_TYPE FROM FACT_TABLE GROUP BY (COST_TYPE); 
/* C)*/
SELECT SUM(TOTAL_POPULATION),AGE_GROUP,MONTH,YEAR FROM FACT_TABLE WHERE MONTH='APR' AND YEAR=2020 GROUP BY (AGE_GROUP,MONTH,YEAR);
/* D)*/
SELECT SUM(TOTAL_SERVICE_COST),SUBURB,S.SERVICE_NAME FROM FACT_TABLE F JOIN SERVICE_DIM S ON F.SERVICE_ID=S.SERVICE_ID WHERE S.SERVICE_NAME='general medical consultations' GROUP BY(SUBURB,SERVICE_NAME);
